proxies:
- name: 'ARISTA #1'
  type: vless
  server: 195.181.173.199
  port: 8443
  uuid: 394f6981-a782-4779-9a85-e6cf22935d93
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ams1.fromblancwithlove.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #2'
  type: vless
  server: 172.67.65.184
  port: 443
  uuid: 9ce7ac33-5004-40ea-8236-15bc2d25a37c
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: red-dust-51ba.esesesrtf.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: red-dust-51ba.esesesrtf.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #3'
  type: vless
  server: 104.17.186.49
  port: 443
  uuid: 9ce7ac33-5004-40ea-8236-15bc2d25a37c
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: masterserver1.aertyuio.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: masterserver1.aertyuio.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #4'
  type: vless
  server: 104.17.17.4
  port: 443
  uuid: 9ce7ac33-5004-40ea-8236-15bc2d25a37c
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: masterserver1.youcom7845.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /
    headers:
      Host: masterserver1.youcom7845.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #5'
  type: vless
  server: 104.26.6.200
  port: 443
  uuid: 9ce7ac33-5004-40ea-8236-15bc2d25a37c
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: masterserver1.majicajjknc.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: masterserver1.majicajjknc.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #6'
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 9ce7ac33-5004-40ea-8236-15bc2d25a37c
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: masterserver1.minaei77.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: masterserver1.minaei77.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #7'
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 73796e63-0000-4000-8000-000000000000
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: icy-rice-3089.lalaeippp4.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: icy-rice-3089.lalaeippp4.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #8'
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 510c038f-5deb-4ecd-8743-790e8cb588de
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: black-frost-b296.amokalam.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: black-frost-b296.amokalam.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #9'
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 9f2ecebe-3a52-460e-80ac-74a21fffdaf7
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: royal-grass-3e36.amoiiiiiiiiiii.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1-MaSTeRSeRVeR1
    headers:
      Host: royal-grass-3e36.amoiiiiiiiiiii.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #10'
  type: vless
  server: 94.182.107.242
  port: 38800
  uuid: 331c4777-2c36-42ab-87af-f456efbe957c
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 94.182.107.242
  client-fingerprint: chrome
- name: 'ARISTA #11'
  type: vless
  server: 141.193.213.10
  port: 443
  uuid: fc965ad9-bdd7-4815-ad71-b39ec5972dc1
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: octopusss4.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /tsghdws
    headers:
      Host: octopusss4.com
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #12'
  type: vless
  server: cdn7-39.vk-cdnvideo.com
  port: 8443
  uuid: 931729a8-3c20-4841-89a1-f18dc9ce0a6f
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cdn7-39.vk-cdnvideo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #13'
  type: vless
  server: 31.76.91.12
  port: 443
  uuid: dfc0cb9d-f005-41b0-848c-7703bd39d0de
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: jp.s3-cloud.org
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: QVkd5uoSbUA7rHVLtIoJB4iRp4l0zuw0H9qzQBh3lHs
    short-id: 7a3f9e2b1c8d4f6a
- name: 'ARISTA #14'
  type: vless
  server: 151.115.167.188
  port: 8880
  uuid: 8dc7722c-2767-4eea-a28b-2f8daacc07e3
  network: grpc
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 151.115.167.188
  client-fingerprint: chrome
- name: 'ARISTA #15'
  type: vless
  server: speedtest.net
  port: 80
  uuid: cabbfe13-038b-4dbb-9c45-5079c829abfa
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: max-gb1.global.ssl.fastly.net
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: max-gb1.global.ssl.fastly.net
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #16'
  type: vless
  server: muihzxwtdd-19523160218-direct.irgame.co
  port: 443
  uuid: muihzxwtdd
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: muihzxwtdd-19523160218-direct.irgame.co
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #17'
  type: vless
  server: 203.18.98.248
  port: 443
  uuid: a5b51f6e-3637-47c4-ba6b-85e8355b9ad9
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: chatgpt.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: 2TrPdiGqUxSvsACQN1GDLTS2lAiuUGicwNqH9Byqx1o
    short-id: 47174804ee8a1dae
- name: 'ARISTA #18'
  type: vless
  server: 91.107.166.66
  port: 44728
  uuid: 13feb2c9-7fb6-4319-a406-83de2f05aaa7
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: aws.amazon.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: rOoltQhWKsF2PCZV4fIkxxsl7tg6-WUmQWMqJHEF6SM
    short-id: dbb6ea0b
- name: 'ARISTA #19'
  type: vless
  server: 169.40.32.127
  port: 28688
  uuid: 5da76c9b-2e7f-46f4-9392-83c651d03a55
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 169.40.32.127
  client-fingerprint: chrome
- name: 'ARISTA #20'
  type: vless
  server: 162.249.126.75
  port: 8443
  uuid: 931729a8-3c20-4841-89a1-f18dc9ce0a6f
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cdn3-87.vk-cdnvideo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #21'
  type: vless
  server: sca16.myfymain.com
  port: 8880
  uuid: 8dc7722c-2767-4eea-a28b-2f8daacc07e3
  network: grpc
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sca16.myfymain.com
  client-fingerprint: chrome
- name: 'ARISTA #22'
  type: vless
  server: euro.connectingissues.ir
  port: 80
  uuid: e7c9c831-b26f-4b73-ba2b-9f372eaed956
  network: xhttp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: shirin-kose.de
  client-fingerprint: chrome
- name: 'ARISTA #23'
  type: vless
  server: 151.115.164.36
  port: 8880
  uuid: 8dc7722c-2767-4eea-a28b-2f8daacc07e3
  network: grpc
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 151.115.164.36
  client-fingerprint: chrome
- name: 'ARISTA #24'
  type: vless
  server: 46.225.155.159
  port: 1006
  uuid: ad356e93-cc14-417d-9f4e-32376d03f5b7
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: yahoo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: 2iijxUyJsanFAkX0ctH6H4RTW1N4mQYnIsaP8qrbbS8
    short-id: 0c3a409c2ba7d083
- name: 'ARISTA #25'
  type: vless
  server: 162.159.36.5
  port: 443
  uuid: fc965ad9-bdd7-4815-ad71-b39ec5972dc1
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: octopusss4.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /tsghdws
    headers:
      Host: octopusss4.com
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #26'
  type: vless
  server: 152.233.35.228
  port: 8443
  uuid: 394f6981-a782-4779-9a85-e6cf22935d93
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de1.fromblancwithlove.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #27'
  type: vless
  server: 79.133.126.199
  port: 31009
  uuid: 46834b61-a623-42cd-9171-a94572ffe56c
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 79.133.126.199
  client-fingerprint: chrome
- name: 'ARISTA #28'
  type: vless
  server: 185.229.191.183
  port: 8443
  uuid: 394f6981-a782-4779-9a85-e6cf22935d93
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ams1.fromblancwithlove.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #29'
  type: vless
  server: 46.229.243.131
  port: 8443
  uuid: 931729a8-3c20-4841-89a1-f18dc9ce0a6f
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cdn3-87.vk-cdnvideo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #30'
  type: vless
  server: 95.133.245.170
  port: 8443
  uuid: 931729a8-3c20-4841-89a1-f18dc9ce0a6f
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cdn3-87.vk-cdnvideo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #31'
  type: vless
  server: 45.157.232.164
  port: 15198
  uuid: ee493449-df40-4d17-9a50-cf28c9288923
  network: xhttp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.varzesh3.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: 8lGfxA5t5bj7JNPYgLxmeta47c7He4M0i9gYoaTAvAo
    short-id: f4ad
- name: 'ARISTA #32'
  type: vless
  server: 104.17.122.123
  port: 2083
  uuid: 6c22648a-18f5-4249-9ace-72a1639d4190
  network: xhttp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ziba.velizor.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #33'
  type: vless
  server: join-masterserver.lehefe6790.workers.dev
  port: 443
  uuid: f328ce2e-7410-4202-b99f-5f56c6012df5
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: join-masterserver.lehefe6790.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: ws
    headers:
      Host: join-masterserver.lehefe6790.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #34'
  type: vless
  server: 104.21.18.41
  port: 443
  uuid: dd0cfef0-fda9-47ec-8a65-49d7bc004f82
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: nic3-1.workers.dev
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /--Telegram---@MiTiVPN/---@MiTiVPN
    headers:
      Host: mitivpn-2.nic3-1.workers.dev
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #35'
  type: vless
  server: eedf07fd7be44fcd.reni-z1.maf-tahas.ir
  port: 8585
  uuid: 31351ae7-e506-43d3-9fcf-246c5248d336
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: yahoo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: 58yfyRJyku8oddKvCIBHz0K8LrTWKr3qTe-DMUcrWEg
    short-id: ea0e387f2b260e0d
- name: 'ARISTA #36'
  type: vless
  server: poli.appleseraj.ir
  port: 8443
  uuid: 2f2af478-e99b-4dd4-a6ff-d3b94449b483
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: emarate.appleseraj.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /?ed=2048
    headers:
      Host: emarate.appleseraj.ir
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #37'
  type: vless
  server: estonia.izumii.ir
  port: 9063
  uuid: 1b82e854-c1df-4aa4-a6d4-57153cc0fad8
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: play.google.com
  client-fingerprint: chrome
- name: 'ARISTA #38'
  type: vless
  server: 152.233.35.228
  port: 8443
  uuid: 394f6981-a782-4779-9a85-e6cf22935d93
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de1.fromblancwithlove.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #39'
  type: vless
  server: 45.130.125.69
  port: 2096
  uuid: 5e8c894b-1efa-48d4-85ee-9daf5d574c16
  network: grpc
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bad-AppLicatIon22nBd8j5OK.CArBoNbLaCkBmw.Ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  grpc-opts:
    grpc-service-name: irannewsdaily.com.hamshahrionline.ir.irdiplomacy.ir.irandaily.ir.alef.ir.rajanews.com.irannewsdaily.com
- name: 'ARISTA #40'
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 0b2f19d7-451d-454b-a09f-032a1cfc2394
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: watson.ferrarikingfr.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /watson
    headers:
      Host: watson.ferrarikingfr.ir
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #41'
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: a2ad7375-5610-411e-a7d0-e13d505c2ebc
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: watson.ferrarikingfr.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /@FragConfig-@FragConfig-@FragConfig-@FragConfig
    headers:
      Host: watson.ferrarikingfr.ir
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #42'
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: a2ad7375-5610-411e-a7d0-e13d505c2ebc
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: watson.ferrarikingfr.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /watson
    headers:
      Host: watson.ferrarikingfr.ir
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #43'
  type: vless
  server: sedfxyz.s16.viptelbot.top
  port: 80
  uuid: 0251d827-a6c8-41cf-ae3d-4a3540d96ad5
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sedfxyz.s16.viptelbot.top
  client-fingerprint: chrome
  ws-opts:
    path: /watson.php
    headers:
      Host: sedfxyz.s16.viptelbot.top
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #44'
  type: vless
  server: sedfxyz.s16.viptelbot.top
  port: 80
  uuid: a40d3a03-a6b7-4e70-afdb-f23f1699a8d2
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sedfxyz.s16.viptelbot.top
  client-fingerprint: chrome
  ws-opts:
    path: /watson.php
    headers:
      Host: sedfxyz.s16.viptelbot.top
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #45'
  type: vless
  server: 216.24.57.210
  port: 443
  uuid: a7ae80ce-7204-4836-90fe-2ce21e129eac
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: watson.ferrarikingfr.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /watson
    headers:
      Host: watson.ferrarikingfr.ir
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #46'
  type: vless
  server: 143.246.138.66
  port: 37216
  uuid: '%40awlix_ir'
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: snapp.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: U7KJGthK463UeOqHkjWfcsMo5Xv-Nf8avLTwbMlL0D4
    short-id: c2
- name: 'ARISTA #47'
  type: vless
  server: 85.202.160.238
  port: 85
  uuid: '%40awlix_ir'
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 85.202.160.238
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: 85.202.160.238
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
- name: 'ARISTA #48'
  type: vless
  server: cdn7-39.vk-cdnvideo.com
  port: 8443
  uuid: 931729a8-3c20-4841-89a1-f18dc9ce0a6f
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cdn7-39.vk-cdnvideo.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #49'
  type: vless
  server: 91.107.185.59
  port: 44728
  uuid: 72f21e0a-1690-4bab-bbf8-2f6239a6bef9
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: aws.amazon.com
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  alpn:
  - h2
  - http/1.1
  reality-opts:
    public-key: rOoltQhWKsF2PCZV4fIkxxsl7tg6-WUmQWMqJHEF6SM
    short-id: dbb6ea0b
- name: 'ARISTA #50'
  type: vless
  server: ser7.fredomiran.com
  port: 443
  uuid: 44f7eb71-de22-4a9c-8d5a-64fb7115c82f
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: panel.fredomiran.com
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /
    headers:
      Host: panel.fredomiran.com
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
total: 50
source: combined
category: vless
tier: '50'
